package by.pvt.heldyieu.parsers.enums;

public enum XMLTagsEnum {
	MOBILEPROVIDER, TARIFFS, TARIFFFORINTERNET,TARIFFFORCALLS, TARIFF, NAME, OPERATOR_NAME, PAYROLL, CALL_PRICES, PRICES, SMS_PRICE,  FREE_GYGABYTES, 
	PARAMETERS, FREE_MINUTES, FAVOURITE_NUMBER, TARIFFICATION, SUBSCRIBE_COST
}
